name: buf-lint
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.7.0
      - uses: bufbuild/buf-lint-action@v1.0.1
      - uses: bufbuild/buf-breaking-action@v1.1.0
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1'
