name: buf-push
on:
  push:
    branches:
      - main
jobs:
  push-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.11.0
      - uses: bufbuild/buf-lint-action@v1.0.3
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1'
      - uses: bufbuild/buf-push-action@v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
